# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: zx action

on:
  workflow_dispatch:

jobs:
  action:
    strategy:
      matrix:
        os: 
          - ubuntu-22.04
          - windows-2022
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: masinc/test-custom-action@main
        with:
          runtime: zx
